name: Update core dependencies
on:
  workflow_dispatch: null
  schedule:
    # https://crontab.guru/#5_8_*_*_*
    - cron: "5 8 * * *"

# Conditional runs
# https://stackoverflow.com/a/61832535/2460034
jobs:
  update-webref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
          cache: npm

      # Use ncu to detect major version changes
      - run: npm i -g npm-check-updates
      - run: ncu -u
      - run: npm i
      - run: git restore package.json
      - run: npm run build && npm run baseline-accept
      - id: git-diff
        run: git diff --quiet HEAD baselines
        continue-on-error: true
      - uses: peter-evans/create-pull-request@v3
        if: ${{ steps.git-diff.outcome == 'failure' }}
        with:
          commit-message: "🤖 Update core dependencies"
          title: "Update core dependencies"
          push-to-fork: typescript-bot/TypeScript-DOM-lib-generator
          branch: update-core-deps
          token: ${{ secrets.TS_GITHUB_BOT_AUTH }}
